const changed = (
  before: Record<string, unknown>,
  after: Record<string, unknown>,
  fields: string[],
): boolean =>
  fields.some(
    (field) => JSON.stringify(before[field]) !== JSON.stringify(after[field]),
  );

const BUCKET_CONTENT_FIELDS = [
  'title',
  'description',
  'items',
  'aggregate',
  'pricingPolicy',
  'orderState',
];

/** Suppress the generic update generated by access materialization itself. */
export const isAccessOnlyBucketUpdate = (
  before: Record<string, unknown>,
  after: Record<string, unknown>,
): boolean =>
  typeof after.lastSocialAccessChangeAt === 'string' &&
  before.lastSocialAccessChangeAt !== after.lastSocialAccessChangeAt &&
  !changed(before, after, BUCKET_CONTENT_FIELDS);

interface JoinCodeInviteLike {
  status?: unknown;
  acceptedBy?: unknown;
  createdBy?: unknown;
}

export const isJoinCodeInviteAcceptance = (
  before: JoinCodeInviteLike,
  after: JoinCodeInviteLike,
): boolean =>
  before.status === 'pending' &&
  after.status === 'accepted' &&
  typeof after.acceptedBy === 'string' &&
  after.acceptedBy.length > 0 &&
  typeof after.createdBy === 'string' &&
  after.createdBy.length > 0;
