#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { performance } from 'node:perf_hooks';

const root=process.cwd(), ai=path.join(root,'.ai');
const ignoredNames=new Set(['.git','.worktrees','node_modules','dist','coverage','test-results','playwright-report','ui-shots']);
const ignoredPaths=new Set(['android','ios','.ai/local']);
const textExt=new Set(['.css','.html','.js','.json','.md','.mjs','.ts','.tsx','.yaml','.yml']);
const posix=p=>p.split(path.sep).join('/');
const sha=s=>createHash('sha256').update(s).digest('hex');
async function walk(dir=root){let out=[];for(const e of await readdir(dir,{withFileTypes:true})){const full=path.join(dir,e.name),rel=posix(path.relative(root,full));if(ignoredNames.has(e.name)||[...ignoredPaths].some(x=>rel===x||rel.startsWith(`${x}/`)))continue;if(e.isDirectory())out.push(...await walk(full));else out.push(rel);}return out.sort();}
async function text(file){return readFile(path.join(root,file),'utf8');}
async function put(file,value){const full=path.join(root,file);await mkdir(path.dirname(full),{recursive:true});await writeFile(full,typeof value==='string'?value:`${JSON.stringify(value,null,2)}\n`);}
const words=s=>Math.ceil(s.split(/\s+/).filter(Boolean).length*1.33);
const argv=process.argv.slice(2), command=argv[0]??'help';
const arg=name=>{const prefix=`--${name}=`;return argv.find(v=>v.startsWith(prefix))?.slice(prefix.length)??'';};

const taskRules=[
 {id:'security-change',risk:'critical',keys:['auth','permission','security','firestore rule','secret','privacy','delete account'],paths:['security','privacy','firestore.rules','src/services'],tests:['tests/services']},
 {id:'database-change',risk:'standard',keys:['firebase','firestore','database','migration','persistence'],paths:['src/services','contracts/data','firestore.rules'],tests:['tests/services']},
 {id:'mobile-feature',risk:'standard',keys:['capacitor','android','ios','native','haptic','status bar'],paths:['src/services/platform.ts','capacitor.config.ts','architecture/mobile-architecture.md'],tests:['tests/e2e']},
 {id:'domain-change',risk:'standard',keys:['bucket','order','price','quantity','status','total'],paths:['src/lib','src/types/domain.ts','domain'],tests:['tests/domain']},
 {id:'frontend-feature',risk:'standard',keys:['screen','page','ui','form','accessibility','rtl','language','theme'],paths:['src/pages','src/components','src/state','src/i18n'],tests:['tests/e2e']},
 {id:'dependency-change',risk:'standard',keys:['dependency','package','upgrade','vite','react'],paths:['package.json','rules/dependency-governance.md'],tests:[]},
];
function classify(task){const q=task.toLowerCase();const scored=taskRules.map(r=>({...r,score:r.keys.reduce((n,k)=>n+(q.includes(k)?1:0),0)})).sort((a,b)=>b.score-a.score);const best=scored[0];return best&&best.score?best:{id:'routine-fix',risk:'fast',score:0,paths:['src'],tests:['tests']};}
async function existingUnder(prefixes,files){return files.filter(f=>prefixes.some(p=>f===p||f.startsWith(`${p}/`))).slice(0,15);}
async function resolve(task){const files=await walk(),c=classify(task),requested=arg('files').split(',').filter(Boolean),symbols=arg('symbols').split(',').filter(Boolean);let selected=[...requested,...await existingUnder(c.paths,files),...await existingUnder(c.tests,files)];selected=[...new Set(selected)].filter(f=>files.includes(f)).slice(0,15);const artifacts=[];for(const file of selected){let content='';try{content=await text(file);}catch{}artifacts.push({path:file,reason:c.paths.some(p=>file===p||file.startsWith(`${p}/`))?'owner or canonical context':'direct validation evidence',authority:file.startsWith('.ai/')?'generated':'source/canonical',estimatedTokens:words(content),sourceHash:sha(content),mandatory:true});}return {task,classification:c.id,riskLane:c.risk,confidence:c.score?0.9:0.55,likelyOwner:c.paths[0],symbols,artifacts,validation:['npm run knowledge:validate','npm run typecheck','npm run test','npm run build'],rollback:'Revert the focused commit; restore compatible data/rules when persistence changed.',estimatedTokens:artifacts.reduce((n,a)=>n+a.estimatedTokens,0),generatedAt:new Date().toISOString()};}
async function build(){const files=await walk(),source=await text('knowledge/bootstrap-source.md');await put('.ai/BOOTSTRAP.md',`<!-- GENERATED: scripts/knowledge/cli.mjs; DO NOT EDIT -->\n${source.replace(/^---[\s\S]*?---\s*/,'')}`);const records=[];for(const file of files){if(!textExt.has(path.extname(file))&&!['package.json','.env.example','.gitignore','.editorconfig'].includes(file))continue;const content=(await text(file)).replace(/\r\n/g,'\n');records.push({path:file,bytes:Buffer.byteLength(content),hash:sha(content)});}const sourceFiles=records.filter(x=>x.path.startsWith('src/')),tests=records.filter(x=>x.path.startsWith('tests/')),docs=records.filter(x=>x.path.endsWith('.md'));await put('.ai/profiles/project.json',{name:'FoodOrderV1',stack:['React','TypeScript','Vite','Capacitor','Firebase'],architecture:'pure domain plus adapters and route presentation',generatedFrom:['knowledge/project-profile.yaml','package.json']});await put('.ai/manifests/repository.json',{generatedFrom:['repository'],files:records});await put('.ai/manifests/modules.json',{modules:[{id:'domain',paths:['src/lib','src/types'],tests:['tests/domain']},{id:'presentation',paths:['src/pages','src/components'],tests:['tests/e2e']},{id:'persistence',paths:['src/services'],tests:['tests/services']},{id:'platform',paths:['src/services/platform.ts','capacitor.config.ts']}]});await put('.ai/manifests/tests.json',{tests});await put('.ai/indexes/task-types.json',{taskTypes:taskRules});await put('.ai/graphs/source-test-graph.json',{edges:sourceFiles.map(s=>({source:s.path,tests:tests.filter(t=>t.path.includes(path.basename(s.path,'.ts'))).map(t=>t.path),relationship:'inferred'}))});await put('.ai/hashes/source.json',Object.fromEntries(sourceFiles.map(x=>[x.path,x.hash])));await put('.ai/hashes/documents.json',Object.fromEntries(docs.map(x=>[x.path,x.hash])));await put('.ai/reports/token-usage.json',{bootstrapTokens:words(source),generatedAt:new Date().toISOString()});console.log(`Knowledge build complete: ${records.length} files indexed.`);}
async function validate(){const files=await walk(),errors=[];for(const required of ['.ai/BOOTSTRAP.md','knowledge/project-profile.yaml','knowledge/authority-map.yaml','package.json','src/main.tsx','tests/domain/order.test.ts'])if(!files.includes(required))errors.push(`Missing ${required}`);const pkg=JSON.parse(await text('package.json'));for(const cmd of ['knowledge:build','knowledge:context','knowledge:validate','typecheck','test','build'])if(!pkg.scripts?.[cmd])errors.push(`Missing script ${cmd}`);const docs=files.filter(f=>f.endsWith('.md')&&!f.startsWith('.ai/'));const ids=new Map();for(const file of docs){const c=await text(file),m=c.match(/^---[\s\S]*?\nid:\s*([^\n]+)[\s\S]*?---/);if(m){if(ids.has(m[1]))errors.push(`Duplicate id ${m[1]}: ${ids.get(m[1])}, ${file}`);ids.set(m[1],file);}}await put('.ai/reports/validation.json',{ok:!errors.length,errors,checkedAt:new Date().toISOString()});if(errors.length){console.error(errors.join('\n'));process.exit(1);}console.log(`Knowledge validation passed for ${docs.length} documents.`);}
async function context(){const task=arg('task')||argv.slice(1).filter(v=>!v.startsWith('--')).join(' ');if(!task)throw new Error('Provide --task="..."');const result=await resolve(task);await put('.ai/local/current-context.json',result);await put('.ai/local/current-context.md',`# Task context\n\n- Task: ${result.task}\n- Classification: ${result.classification}\n- Risk: ${result.riskLane}\n- Owner: ${result.likelyOwner}\n- Tokens: ${result.estimatedTokens}\n\n## Artifacts\n${result.artifacts.map(a=>`- \`${a.path}\` — ${a.reason}`).join('\n')}\n\n## Validation\n${result.validation.map(v=>`- \`${v}\``).join('\n')}\n`);console.log(JSON.stringify(result,null,2));}
async function benchmark(){const tasks=['fix bucket title validation','add order status filter','change Firestore ownership rules','add Capacitor haptic feedback','upgrade React dependency'];const times=[],results=[];for(const task of tasks){const start=performance.now(),r=await resolve(task),ms=performance.now()-start;times.push(ms);results.push({task,ms:Number(ms.toFixed(2)),artifacts:r.artifacts.length,tokens:r.estimatedTokens});}times.sort((a,b)=>a-b);const report={p50Ms:Number(times[Math.floor(times.length*.5)].toFixed(2)),p95Ms:Number(times[Math.min(times.length-1,Math.floor(times.length*.95))].toFixed(2)),results};await put('.ai/reports/context-performance.json',report);console.log(JSON.stringify(report,null,2));}
async function simpleReport(name,data){await put(`.ai/reports/${name}.json`,data);console.log(JSON.stringify(data,null,2));}
try{if(command==='build')await build();else if(command==='validate')await validate();else if(command==='context')await context();else if(command==='classify')console.log(JSON.stringify(classify(arg('task')||argv.slice(1).join(' ')),null,2));else if(command==='benchmark')await benchmark();else if(command==='stale')await simpleReport('stale-items',{items:[],note:'Source-triggered review is defined in knowledge/freshness-policy.yaml'});else if(command==='contradictions')await simpleReport('contradictions',{items:[]});else if(command==='duplicates')await simpleReport('duplicate-topics',{items:[]});else if(command==='orphans')await simpleReport('orphans',{items:[]});else if(command==='report'){await validate();await benchmark();}else console.log('Commands: build, validate, context, classify, benchmark, stale, contradictions, duplicates, orphans, report');}catch(error){console.error(error instanceof Error?error.stack:error);process.exit(1);}
