const changed = (before, after, fields) => fields.some((field) => JSON.stringify(before[field]) !== JSON.stringify(after[field]));
const BUCKET_CONTENT_FIELDS = [
    'title',
    'description',
    'items',
    'aggregate',
    'pricingPolicy',
    'orderState',
];
/** Suppress the generic update generated by access materialization itself. */
export const isAccessOnlyBucketUpdate = (before, after) => typeof after.lastSocialAccessChangeAt === 'string' &&
    before.lastSocialAccessChangeAt !== after.lastSocialAccessChangeAt &&
    !changed(before, after, BUCKET_CONTENT_FIELDS);
export const isJoinCodeInviteAcceptance = (before, after) => before.status === 'pending' &&
    after.status === 'accepted' &&
    typeof after.acceptedBy === 'string' &&
    after.acceptedBy.length > 0 &&
    typeof after.createdBy === 'string' &&
    after.createdBy.length > 0;
