import { Save } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { useApp } from '@/state/AppContext';
import type { CurrencyCode, Locale, Theme } from '@/types/domain';
const currencies: CurrencyCode[] = ['EGP', 'USD', 'EUR', 'GBP', 'SAR', 'AED'];
export function SettingsPage() {
  const { profile, storageMode, online, t, saveProfile } = useApp();
  const [fullName, setFullName] = useState(profile?.fullName ?? ''); const [locale, setLocale] = useState<Locale>(profile?.locale ?? 'en'); const [theme, setTheme] = useState<Theme>(profile?.theme ?? 'system'); const [currency, setCurrency] = useState<CurrencyCode>(profile?.defaultCurrency ?? 'EGP'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (profile) { setFullName(profile.fullName); setLocale(profile.locale); setTheme(profile.theme); setCurrency(profile.defaultCurrency); } }, [profile]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!fullName.trim()) return setError('Full name is required.'); try { setBusy(true); setError(''); await saveProfile({ fullName: fullName.trim(), locale, theme, defaultCurrency: currency }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save settings.'); } finally { setBusy(false); } };
  return <div className="page narrow stack-lg"><div className="page-heading"><div><p className="eyebrow">{t('profile')}</p><h1>{t('settings')}</h1></div></div><form className="stack-lg" onSubmit={(event) => void submit(event)}><section className="section-card form-grid"><label>{t('fullName')}<input value={fullName} onChange={(event) => setFullName(event.target.value)} /></label><label>{t('email')}<input value={profile?.email ?? ''} disabled /></label><label>{t('language')}<select value={locale} onChange={(event) => setLocale(event.target.value as Locale)}><option value="en">English</option><option value="ar">العربية</option></select></label><label>{t('theme')}<select value={theme} onChange={(event) => setTheme(event.target.value as Theme)}><option value="system">{t('system')}</option><option value="light">{t('light')}</option><option value="dark">{t('dark')}</option></select></label><label>{t('currency')}<select value={currency} onChange={(event) => setCurrency(event.target.value as CurrencyCode)}>{currencies.map((code) => <option key={code}>{code}</option>)}</select></label></section><section className="section-card metadata-grid"><div><span>{t('storageMode')}</span><strong>{storageMode === 'firebase' ? t('firebaseMode') : t('localMode')}</strong></div><div><span>Connection</span><strong>{online ? t('online') : t('offline')}</strong></div></section>{error ? <p className="form-error">{error}</p> : null}<div className="sticky-actions"><button className="button" disabled={busy}><Save />{busy ? t('loading') : t('save')}</button></div></form></div>;
}
