/** Cloud Firestore surface used by application source. */
export {
  collection,
  deleteDoc,
  doc,
  documentId,
  type DocumentReference,
  type FieldPath,
  type Firestore,
  getDoc,
  getDocs,
  initializeFirestore,
  limit,
  orderBy,
  persistentLocalCache,
  persistentMultipleTabManager,
  query,
  type QueryConstraint,
  runTransaction,
  setDoc,
  startAfter,
  where,
  writeBatch,
} from 'firebase/firestore';
