import { TELEMETRY_PURPOSE } from '../enums/telemetry.enums';

export const ANALYTICS_EVENT = {
  inviteLinkCreated: 'invite_link_created',
  inviteLinkShared: 'invite_link_shared',
  publicInviteViewed: 'public_invite_viewed',
  guestFlowStarted: 'guest_flow_started',
  authFlowStarted: 'auth_flow_started',
  registrationCompleted: 'registration_completed',
  guestAccountLinked: 'guest_account_linked',
  firstMenuCreated: 'first_menu_created',
  firstSessionOpened: 'first_session_opened',
  firstInviteShared: 'first_invite_shared',
  firstParticipantJoined: 'first_participant_joined',
  firstContributionSubmitted: 'first_contribution_submitted',
  firstOrderFinalized: 'first_order_finalized',
  firstSessionSettled: 'first_session_settled',
  sessionOpened: 'session_opened',
  contributionChanged: 'contribution_changed',
  participantMarkedDone: 'participant_marked_done',
  participantSkipped: 'participant_skipped',
  reminderSent: 'reminder_sent',
  repeatSelectionUsed: 'repeat_selection_used',
  recurringScheduleCreated: 'recurring_schedule_created',
  restaurantHandoffExported: 'restaurant_handoff_exported',
  receiptReconciled: 'receipt_reconciled',
  paymentDeclared: 'payment_declared',
  paymentVerified: 'payment_verified',
  planViewed: 'plan_viewed',
  upgradePromptViewed: 'upgrade_prompt_viewed',
  upgradeClicked: 'upgrade_clicked',
  trialStarted: 'trial_started',
  checkoutStarted: 'checkout_started',
  checkoutCompleted: 'checkout_completed',
  checkoutFailed: 'checkout_failed',
  subscriptionChanged: 'subscription_changed',
  entitlementBlocked: 'entitlement_blocked',
  usageLimitReached: 'usage_limit_reached',
  gatewayError: 'gateway_error',
  callableError: 'callable_error',
  scheduleFailure: 'schedule_failure',
  syncConflict: 'sync_conflict',
  offlineQueueFailed: 'offline_queue_failed',
  attachmentUploadFailed: 'attachment_upload_failed',
  migrationFailure: 'migration_failure',
  featureFlagExposed: 'feature_flag_exposed',
} as const;

export type AnalyticsEventName =
  (typeof ANALYTICS_EVENT)[keyof typeof ANALYTICS_EVENT];

export const ANALYTICS_EVENT_PURPOSE = {
  [ANALYTICS_EVENT.inviteLinkCreated]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.inviteLinkShared]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.publicInviteViewed]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.guestFlowStarted]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.authFlowStarted]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.registrationCompleted]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.guestAccountLinked]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.firstMenuCreated]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.firstSessionOpened]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.firstInviteShared]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.firstParticipantJoined]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.firstContributionSubmitted]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.firstOrderFinalized]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.firstSessionSettled]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.sessionOpened]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.contributionChanged]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.participantMarkedDone]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.participantSkipped]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.reminderSent]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.repeatSelectionUsed]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.recurringScheduleCreated]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.restaurantHandoffExported]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.receiptReconciled]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.paymentDeclared]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.paymentVerified]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.planViewed]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.upgradePromptViewed]: TELEMETRY_PURPOSE.marketing,
  [ANALYTICS_EVENT.upgradeClicked]: TELEMETRY_PURPOSE.marketing,
  [ANALYTICS_EVENT.trialStarted]: TELEMETRY_PURPOSE.marketing,
  [ANALYTICS_EVENT.checkoutStarted]: TELEMETRY_PURPOSE.marketing,
  [ANALYTICS_EVENT.checkoutCompleted]: TELEMETRY_PURPOSE.marketing,
  [ANALYTICS_EVENT.checkoutFailed]: TELEMETRY_PURPOSE.operational,
  [ANALYTICS_EVENT.subscriptionChanged]: TELEMETRY_PURPOSE.operational,
  [ANALYTICS_EVENT.entitlementBlocked]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.usageLimitReached]: TELEMETRY_PURPOSE.product,
  [ANALYTICS_EVENT.gatewayError]: TELEMETRY_PURPOSE.operational,
  [ANALYTICS_EVENT.callableError]: TELEMETRY_PURPOSE.operational,
  [ANALYTICS_EVENT.scheduleFailure]: TELEMETRY_PURPOSE.operational,
  [ANALYTICS_EVENT.syncConflict]: TELEMETRY_PURPOSE.operational,
  [ANALYTICS_EVENT.offlineQueueFailed]: TELEMETRY_PURPOSE.operational,
  [ANALYTICS_EVENT.attachmentUploadFailed]: TELEMETRY_PURPOSE.operational,
  [ANALYTICS_EVENT.migrationFailure]: TELEMETRY_PURPOSE.operational,
  [ANALYTICS_EVENT.featureFlagExposed]: TELEMETRY_PURPOSE.product,
} as const;

export const FORBIDDEN_ANALYTICS_PROPERTY_KEYS = new Set([
  'address',
  'attachment',
  'attachmentPath',
  'attachmentUrl',
  'displayName',
  'email',
  'fullName',
  'inviteToken',
  'message',
  'note',
  'password',
  'paymentProof',
  'paymentReference',
  'phone',
  'rawError',
  'token',
]);
